language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_4db1576f9513_key -iv $encrypted_4db1576f9513_iv
  -in settings.json.enc -out settings.json -d
- openssl aes-256-cbc -K $encrypted_4db1576f9513_key -iv $encrypted_4db1576f9513_iv
  -in mup.json.enc -out mup.json -d
- npm install -g mupx
- curl https://install.meteor.com | /bin/sh
branches:
  only:
  - master
script:
- mupx deploy
