language: node_js
node_js:
- '0.12'
before_install:
- sudo apt-get install expect
- curl https://install.meteor.com | /bin/sh
#build all branches, uncomment below to change it
#branches:
#  only:
#  - master
script:
  - "expect deploy.exp"